# This configuration builds a Docker image and stores logs in a GCS bucket
#
# build command:
#   gcloud builds submit . \
#    --region=$LOCATION \
#    --substitutions=_REPOSITORY=$REPOSITORY,\
#    _IMAGE_NAME=$IMAGE_NAME,\
#    _LOG_BUCKET=$LOG_BUCKET

substitutions:
  _REPOSITORY: $_REPOSITORY
  _IMAGE_NAME: $_IMAGE_NAME
  _LOG_BUCKET: $_LOG_BUCKET
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}$COMMIT_SHA'
  - '.'
  # - '-f'
  # - '/'
  # - '$_DOCKERFILE_PATH'
  # - '.'
images: ['$LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE_NAME$COMMIT_SHA']
logsBucket: 'gs://$_LOG_BUCKET/demo-cloudbuild-logs'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
